---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Learn well your grammar,

And never stammar,

Write well and neatly,

And sing most sweetly,

Be enterprising,

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
He saw her from the bottom of the stairs Before she saw him. She was starting down, Looking back over her shoulder at some fear. She took a doubtful step and then undid it To raise herself and look again. He spoke
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
From childhood’s hour I have not been As others were – I have not seen As others saw – I could not bring My passions from a common spring – From the same source I have not taken My sorrow – I could not awaken My heart to joy at the same tone – And all I lov’d – I lov’d alone – Then – in my childhood – in the dawn Of a most stormy life – was drawn From ev’ry depth of good and ill The mystery which binds me still – From the torrent, or the fountain –
